baseURL = 'https://glb-inovation.github.io'
languageCode = 'pt-br'
title = 'GLB Inovação'
theme = 'FixIt'
sectionPagesMenu = 'main'
[params.header.title]
      # URL of the LOGO
      logo = 'content\images\heliotrobot.jpeg'
