baseURL = 'https://glb-inovation.github.io'
languageCode = 'pt-br'
title = 'GLB Inovação'
theme = 'FixIt'
sectionPagesMenu = 'main'
[params.header.title]
      # URL of the LOGO
      logo = 'https://github.com/GLB-Inovation/GLB-Inovation.github.io/blob/main/content/images/heliotrobot.jpeg?raw=true'
